# 网站标题
title: 網頁製作，你不可不知道的事
# 网站标题后缀
# suffix: Quiet
# 作者名称(会显示在首页文章下面)
author: Sunny
# 首页简介（显示在首页顶部Logo的那句话）
# home_describe: A COLLEGE STUDENT WITH IDEALS AND BELIEFS.
# 网站关键字
keyword: 網頁設計,HTML,CSS,Vue,ElemenuUI,前端,前端設計師
is_article_img: false  #false是否开启文章背景图显示(随机图片)
# 网站描述
web_description: 相信很多人在製作網頁的時候，可能會遇到與我相同的問題，網站會分享我在製作時所遇到的網頁設計及前端問題
# 导航名称
menus_title:
  home: 首頁
  # archive: ARCHIVE
  categories: 文章分類
  tags: 標籤
  # links: LINKS
  about: 關於我
# 导航 （不建议修改）
menus:
  home: /
  # archive: /archives
  categories: /categories
  tags: /tags
  # links: /links
  about: /about
  
# logo
logo: /image/logo.png
# 网页標籤上那个小图标 一定要用本地存储
icon: /image/favicon.ico
# 每个页面上面的图表
topIcon:
  homeIcon: "/image/logo.png"
  # archivesIcon: "https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imgicon-remixicon.svg"
  tagIcon: "https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imgtags.svg"
  # linksIcon: "https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imga20r7-cftji.svg"
  categoriesIcon: "https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imgblogmyCategory.svg"
  
# 標籤页显示多少个標籤
tagsNum: 1000
# 网页访问统计
web_analytics:  
  enable: false #需要改为true
  baidu: 4b5fe1472f22fa  # （替换）百度统计的 Key，参见 https://tongji.baidu.com/sc-web/10000033910/home/site/getjs?siteId=13751376 代码获取中 hm.js? 后边的字符串
# 底部显示的图标（github 或者其他）
bottomIcon: 
  #可以多个
  - {
    #描述名称
    name: 'Github',
    #图标    
    iconLink: 'https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imggithub.png',
    #跳转链接    
    toUrl: 'https://github.com/wangsunny0403'
  }
# 友情链接
# linksList:
#   - {
#     title: '乔越博客',
#     intro: '收藏回忆与分享技术的地方',
#     link: 'https://www.79bk.cn/',
#     image: 'https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imgIMG_7327.jpeg'
#   }
# 文字内点击图片放大相关配置
picture:
  # 蒙版的颜色也就是 打开图片背景 显示的颜色
  colour: '#333'
  # 透明度
  opacity: 0.5
  # 图片角度 就是显示图片的角度
  imgRadius: "10px"
#默认的cover (默认缩略图) 在没有填写（这里可以替换（可以是api也可以是固定的图））
default_cover: https://api.ixiaowai.cn/gqapi/gqapi.php